manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: beekeeb
      url-base: https://github.com/beekeeb
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: geeksville
      url-base: https://github.com/geeksville
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 5138c6fb14783b756c5a3e61581625c700f3555b
      import: app/west.yml
    - name: zmk-keyboard-toucan
      remote: beekeeb
      revision: 7154e0187128e493cd15785a18af1546419d5bb1
      path: modules/zmk-keyboard-toucan
    - name: cirque-input-module
      remote: geeksville
      revision: toucan
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: v0.3
  self:
    path: config
